"""Cached estimation examples for CAG context injection."""

ESTIMATION_EXAMPLES: list[dict] = [
    {
        "meeting_summary": (
            "The customer wants to develop a custom payslip layout for the a3asesor nom application"
            " in order to include up to five additional payroll concepts in the body of the payslip."        
        ),
        "estimation": """\
## Payroll format

### Task Breakdown

| Task | Hours | Cost (EUR) |
|------|------:|------------|
| Requirements analysis and technical design | 4 | 294 |
| Payroll form configuration for a3asesor nom application| 12 | 882 |
| Cobol Coding | 4 | 294 |
| Project management | 4 | 294 |
| Testing (unit, integration, E2E) | 2 | 147 |
| Code review, QA, and bug fixing | 2 | 147 |

### Totals

- **Total hours:** 28
- **Total cost:** 2,058 EUR

### Recommended Team

- 1 Senior Cobol Backend Developer (lead)

### Estimated Duration

**2 weeks** with a one-person development team.""",
    },
    {
        "meeting_summary": (
            "The company's Finance Director wants to integrate the payroll accounting file "
            "with an external invoicing application. To achieve this, they need the accounting"
            " export generated by a3asesor nom to be produced in Excel format, following a"
            " custom structure provided by the client, with a detailed breakdown at "
            "employee-account level. No custom configuration of accounting accounts is "
            "required. "
            
        ),
        "estimation": """\
## Custom Accounting file for a3asesor nom

### Task Breakdown

| Task | Hours | Cost (EUR) |
|------|------:|------------|
| Requirements analysis and technical design | 8 | 588 |
| Excel configuration for accounting in a3asesor nom application| 12 | 882 |
| Cobol Coding | 20 | 1,880 |
| Project management | 6 | 441 |
| Testing (unit, integration, E2E) | 10 | 735 |
| Code review, QA, and bug fixing | 4 | 294 |

### Totals

- **Total hours:** 60
- **Total cost:** 4,410 EUR

### Recommended Team

- 1 Senior Cobol Developer


### Estimated Duration

**5 weeks** with a single Cobol developer.""",
    },
    {
        "meeting_summary": (
            "The company's Finance Director wants to integrate the payroll accounting file "
            "with an external invoicing application. To achieve this, they need the accounting"
            " export generated by a3innuva nomina to be produced in Excel format, following a"
            " custom structure provided by the client, with a detailed breakdown at "
            "employee-account level. No custom configuration of accounting accounts is "
            "required. "
        ),
        "estimation": """\
## Custom Accounting file for a3innuva nomina

### Task Breakdown

| Task | Hours | Cost (EUR) |
|------|------:|------------|
| Requirements analysis and technical design | 16 | 1,176 |
| Excel configuration for accounting in a3asesor nom application| 24 | 1,764 |
| Cobol Coding | 40 | 3,760 |
| Project management | 12 | 882 |
| Testing (unit, integration, E2E) | 20 | 1,470 |
| Code review, QA, and bug fixing | 8 | 588 |

### Totals

- **Total hours:** 120
- **Total cost:** 8,820 EUR

### Recommended Team

- 1 Senior C# Developer (lead)


### Estimated Duration

**12 weeks** with a one-person c# senior developer""",
    },
]


def format_examples_for_prompt(examples: list[dict]) -> str:
    """Format estimation examples into a string suitable for injection into a system prompt."""
    parts: list[str] = []
    for i, example in enumerate(examples, start=1):
        parts.append(
            f"--- EXAMPLE {i} ---\n"
            f"Meeting Summary:\n{example['meeting_summary']}\n\n"
            f"Estimation:\n{example['estimation']}\n"
        )
    return "\n".join(parts)
